### ISSUE TITLE
OB 0.9.0: Check/Update Weapon Mod/Special descriptions

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/dauntless-builder-reforged#113]
Apparently they've changed with OB 0.9.0, didn't have the time to test yet.

**Comment by ScottSlatton** [comment]
Is there a good place to pull this info or do you just grab it from the game itself?

**Comment by atomicptr** [comment]
There is no API for game data, so the data is collected by hand. If you want to use the data we've collected, you can do so here: https://www.dauntless-builder.com/data.json
