### ISSUE TITLE
UE on Stormclaw Sword may be wrong.

### ISSUE THREAD

**Issue by siddagra** [atomicptr/dauntless-builder-reforged#127]
A friend found a bug. The values should be 100%, 200%, 300%. It's 500 for most weapons, but not for the sword.
![image](https://user-images.githubusercontent.com/52118936/70127493-297fab80-16a1-11ea-995a-ff767d9000c3.png)

**Comment by atomicptr** [comment]
Ty for the report, should be fixed in a few minutes :).
