### ISSUE TITLE
dauntless collection

### ISSUE THREAD

**Issue by Nacaroost** [atomicptr/dauntless-builder-reforged#134]
i'm sorry if u are not a dev of dauntless collection but i put a feedback a week ago and don't have answer because when we try to put a build with one piece of malkarion stuff the link don't work so please fix that or if u can't tell to the dev of dauntless collection if u have the time thanks

**Comment by atomicptr** [comment]
Hey, sadly I can't help you with issues relating to dauntless build collection, I forwarded this post to the dev tho.
