### ISSUE TITLE
Set +3/epic rarity cells as default filter

### ISSUE THREAD

**Issue by siddagra** [atomicptr/dauntless-builder-reforged#141]
Most of the time, people use a +3 cell in Dauntless Builder.

As it is right now, only 1 +3 cell can fit on the window before it cuts out.

![image](https://user-images.githubusercontent.com/52118936/77527320-eea0be00-6eb1-11ea-8e77-6dda3750f93d.png)

May be better to:

1. Make the modal longer, as a general improvement to the selection process. No reason why it can't be longer imo.
2. Make +3 cell default filter. So a lot more cells fit in.
![image](https://user-images.githubusercontent.com/52118936/77527459-290a5b00-6eb2-11ea-806e-6be6d833d8d6.png)

Just feedback imho. 
Thank you.

**Comment by atomicptr** [comment]
Closed with #147
