### ISSUE TITLE
Not leveling for prisms description

### ISSUE THREAD

**Issue by medaey** [atomicptr/dauntless-builder-reforged#145]
For each prism, the description varies according to its power.
This is not the case on the site.

Exemple :
In the site Brilliant Prism power 65 (+7) :
![image](https://user-images.githubusercontent.com/16074153/79758115-426dbe00-831d-11ea-984c-1565c2381305.png)

In game prims power 65 (+7) :
![image](https://user-images.githubusercontent.com/16074153/79758793-24ed2400-831e-11ea-9dc8-fd1401df04e0.png)

**Comment by atomicptr** [comment]
Since prisms are gone now, this is redundant.
