### ISSUE TITLE
Kharabak UE doesnt seem to be right

### ISSUE THREAD

**Issue by nova2699** [atomicptr/dauntless-builder-reforged#175]
For the prism, they show as 25 dmg while on axe they are 75, on anything else they are at 50

**Comment by atomicptr** [comment]
Just for documentation:

The prism seems to be +75 base

![image](https://user-images.githubusercontent.com/674705/106363763-d51a9f00-632a-11eb-9514-164073c33a81.png)

Meanwhile the other weapons have +25

![image](https://user-images.githubusercontent.com/674705/106363785-eb285f80-632a-11eb-956e-1d1025df637c.png)

The value might increase when they're power surged though.
