### ISSUE TITLE
Legendary weapons dont select bond weapons

### ISSUE THREAD

**Issue by trickk99** [atomicptr/dauntless-builder-reforged#183]
Selecting any legendary now doesnt select its bond weapons in fiters, also even when manually selecting the weapons (eg. Torgadoro, Hellion, Ember, Charrog) the perks tab doesn't show legendary weapon builds, just normal ones.

**Comment by atomicptr** [comment]
Hm, can you give me an example scenario (like a link) where this doesn't work?

I picked the Torgadoro Axe and I can select a bond weapon just fine:

![image](https://user-images.githubusercontent.com/674705/117844419-f40cc380-b27f-11eb-9c69-2cb87f5aa75f.png)

Which also seems to properly use their perks:

![image](https://user-images.githubusercontent.com/674705/117844479-04bd3980-b280-11eb-9ed0-8aea4c668091.png)

Or do you mean the "My Builds" section which is indeed broken now:

![image](https://user-images.githubusercontent.com/674705/117844628-21597180-b280-11eb-971e-54a4948393b6.png)

(I created a seperate ticket for this in #184)

**Comment by atomicptr** [comment]
Closing this due to no feedback.
