### ISSUE TITLE
Twin Suns chamber/grip selection.

### ISSUE THREAD

**Issue by NathalieWK** [atomicptr/dauntless-builder-reforged#205]
Twin Suns have the option for chambers/grips, which they shouldn't have.

![image](https://user-images.githubusercontent.com/54872220/132109124-fa9643ac-000b-4a43-98b7-24da243dd60d.png)

**Comment by atomicptr** [comment]
Fixed with https://github.com/atomicptr/dauntless-builder/commit/d777c6f704d8b2a6f6a0583843b52ca510dcc855
