### ISSUE TITLE
Weapon Unique abilities in the quick description

### ISSUE THREAD

**Issue by DC6-Games** [atomicptr/dauntless-builder-reforged#222]
### Feature summary

just a minor quality of life thing: A description of each weapon's Unique Effect's while in the weapon selection tab. 

Currently if you don't already know what each of the effects are, you click through each weapon to see what it's effect is. 

### Mockup / Screenshots

I feel like this could be simply added each weapon's description box

![image](https://user-images.githubusercontent.com/91901690/157009746-38c5e449-c97e-4229-85b6-dc1d52fd42da.png)
![image](https://user-images.githubusercontent.com/91901690/157009787-00ecf0a3-f2d5-421b-8a30-13425a77c4ef.png)

**Comment by atomicptr** [comment]
Resolved with #224
