### ISSUE TITLE
Evaluate crowdin.com for localization

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/dauntless-builder-reforged#227]
Never really thought about it, but the system we have right now is obviously almost unusable for someone without technical knowledge. Would be cool if we could integrate with crowdin (or maybe an alternative?).

Idea would be:

1. Create a script that registers all strings from the source language at Crowdin (and also uploads every translation we already have)
2. People can edit things at Crowdin
3. Download data from crowdin and integrate with the data sets again

Links:
* https://github.com/crowdin/crowdin-api-client-js

**Comment by medaey** [comment]
Yep .json file is not for all. 

In other project I use the web site www.transifex.com the .po files generate is use to make .json

Crowdin is better but you need make a request "for open source project" to not pay the service. https://crowdin.com/page/open-source-project-setup-request

Clearly a tool like this is necessary to help the translation.

**Comment by atomicptr** [comment]
https://crowdin.com/project/dauntless-builder

I've managed to upload the current data set to Crowdin, still need to write something to download it again though :).

Edit: This currently does not include Item Data because I'm still limited by the free tier.

Edit 2: This one also looks interesting https://weblate.org/ mostly because of "direct VCS integration"

One weird thing about crowdin is that I had to push everything into a virtual file despite realistically only wanting to upload strings :sweat_smile:
