### ISSUE TITLE
Add a more advanced UI, for making builds

### ISSUE THREAD

**Issue by shulrak** [atomicptr/dauntless-builder-reforged#23]
### Feature summary

I want to be able to select a Perk (or slot) or a weapon/armor type and see all the available armor for it.

### Mockup / Screenshots
Here is a mock up I did when I started working on my dauntless builder. But because of my lack of time I put it on the side.
![mockup_color](https://user-images.githubusercontent.com/25624068/41807617-32743a68-76c9-11e8-84d6-0560990480b5.png)

Orange : The list of all available armors.
  - This is affected by the Perks Filters (green) and the weapon/armor type filters (blue)
  - When hovering on one of the items, it will temporaly update the gear panel (red)
  - When click on the add button (cercle on the right of an item) it will be added to the gear panel

Blue : Weapon/Armor Type filters
  - Those are toggles filters, toggling them just update the main list (orange)

Green : Perks Filters
  - top part there is check box "include slot" I'll come back to later on this.
  - top part, it is a list of the selected perks, selected perks will update the main list (orange), you can also specify the minimum perk level you want.
   - if the checkbox "include slot" is on, it will also filter the item list (orange) base on the type of perks you have selected. (eg : Knockout king + any item that can have a slot with Overpowered.)
  - Half bottom is the list of all possible perks, when you click in on of them, it will be moved to the selected perks list on the top.

Red : The gear panel.
    - top part -> your weapon/armor + the cells. (right square button is to remove the item)
    - bottom part -> the perks stats and we can squeeze in other stuff. like armor/resistance stats on other tabs

Bonus : 
  I want a way to specify what cells I do have and the perks filters can have another option that will filter based on what I have. (Eg : I ask for knockout king +4, it will get me an item with +1 and a cell slot with overpower and knows that I have a +3 available cell.)

Summary : 
I spent quite some time understanding what I was doing most of my time when I was trying to  min-max my gear. That's how I come up with this mock up, I did start to have a simple mock up in React but not time to get something concrete.
Obviously it still need some refinements.

**Comment by Eiscoffee** [comment]
would love it

**Comment by atomicptr** [comment]
While I agree that this UI would be more powerful, I also think it's a lot more complicated and will probably be a massive headache on mobile (which is semi important for me). You can already filter item lists by perks and slots, but you can obviously only do that for the currently selected slot (which is your problem?). A partial solution might be persisting filter selections between open/closing the modal, unsure about the "see everything at once", I can certainly see some benefits to having this... maybe having a seperate "advanced selector" might be a solution, dunno but def. not something that I'd see anytime soon.

**Comment by Eiscoffee** [comment]
well, i guess he is asking for a situation like that:

You know which perks u want to go for, for example:

Aetherhunter+6
Ragerhunter+6
Rage+6

This is the input.

Know these filteres are applied and the output are several Sets which go with these stats.

Am i right?

**Comment by atomicptr** [comment]
I def. see some value to this as an alternative UI or maybe I find a good way to integrate this "how can i get to +6 ???" into the current one, etc.

**Comment by NitroGenX1** [comment]
> well, i guess he is asking for a situation like that:
> 
> You know which perks u want to go for, for example:
> 
> Aetherhunter+6
> Ragerhunter+6
> Rage+6
> 
> This is the input.
> 
> Know these filteres are applied and the output are several Sets which go with these stats.
> 

You know http://dauntlessbuildsearch.ml/ exists. Right?

**Comment by atomicptr** [comment]
I'll close this as #96 describes the primary feature of this request better.
