### ISSUE TITLE
bug in the description perk of the other language than English.

### ISSUE THREAD

**Issue by medaey** [atomicptr/dauntless-builder-reforged#273]
Describes perk Cunning and Evasive Fury don't show correctly in other language.

![image](https://user-images.githubusercontent.com/16074153/181437923-3ec7f358-25bd-4ef6-bec3-280f9a8157bb.png)

Build exemple:
https://www.dauntless-builder.com/b/KBfkTyyC0CXWHLzF7SbhjI8guxni5CR5IpgHAC8Jc65iBCKVU3AuYCxJUkFXVSg

**Comment by atomicptr** [comment]
This is caused by me not having updated the crowdin data (to keep the invalidated data on the site a bit longer), guess I need to update it after all :)
