### ISSUE TITLE
Way to contact the developer?

### ISSUE THREAD

**Issue by asaflivne** [atomicptr/dauntless-builder-reforged#38]
Hey atomicptr,

Is there any email I can reach out to? Or Discord, whichever works better for you.

Thanks!

**Comment by atomicptr** [comment]
I should probably add something like this into the readme...

You can contact me either via email: me@atomicptr.de or discord: Hecate#0001

**Comment by atomicptr** [comment]
I've added some contact details into the Readme with 6a038b6
