### ISSUE TITLE
Sprinter cell shows doubled value

### ISSUE THREAD

**Issue by Electrocute4u** [atomicptr/dauntless-builder-reforged#381]
The sprinter cell shows doubled the value, see attached image below.

![image](https://user-images.githubusercontent.com/25005864/235378335-6052ab9c-333e-44d2-ba20-222515a256f2.png)
Correct values are half of the values, probably a mistype, but now you are aware of it.

**Comment by ds-exe** [comment]
Correct values from in game
![image](https://user-images.githubusercontent.com/33606227/235379222-feab9b20-2b17-4f91-808e-513458fcd419.png)

**Comment by atomicptr** [comment]
Fixed with #382
