### ISSUE TITLE
PackHunter has a typo, file is called "PactHunter.yml"

### ISSUE THREAD

**Issue by Electrocute4u** [atomicptr/dauntless-builder-reforged#458]
The cdn for Pack Hunter cell has a typo in the yml filename, where its spelled "Pack" and not "Pact".
Direct URL: https://cdn.jsdelivr.net/gh/atomicptr/dauntless-builder@master/data/perks/PactHunter.yml

**Comment by atomicptr** [comment]
True, I'll fix this although you are technically not supposed to access the .yml data directly as it will be removed in the future, the same data is also available at https://www.dauntless-builder.com/data.json perks > Pack Hunter (where it was always correct)

![image](https://github.com/atomicptr/dauntless-builder/assets/674705/b066d7cf-0531-440c-bd93-68d1cef9e3ce)

**Comment by atomicptr** [comment]
Fixed with d3ec4a1a26c4d189792e7bd2e824df4cb080756b
