### ISSUE TITLE
Deadeye Grip Barbed perk

### ISSUE THREAD

**Issue by Quest27** [atomicptr/dauntless-builder-reforged#59]
### Deadeye Grip [Gloves]

The gloves of this set has the following perks in game: "+1 Savagery, +1 Barbed"
However in the database it has the following perks: "+1 Savagery, +2 Barbed"

**Comment by atomicptr** [comment]
The ingame stats are +2 Barbed and +1 Savagery (for +10) tho:

![](https://media.discordapp.net/attachments/75198663810363392/501338617168396288/unknown.png)

(Minus the +3 Savagery Cell)

**Comment by atomicptr** [comment]
Since there was no answer I presume this is solved.
