### ISSUE TITLE
Keep cell equipped when changing to a new item with the same cell slot type

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/dauntless-builder-reforged#71]
When switching between Weapon A (Power, Power) to weapon B (Power, Technique) the first cell should stay equipped and obviously this should be the case for anything. This feels esp. cumbersome on lanterns, since all of them are Utility anyway.

**Comment by IvanKarpan** [comment]
I did this for weapons, armour and lanterns. Immediately realized it'd be cool to have the same for weapon specials and mods and other repeaters sub-parts... That is a different feature though me thinks. :)

**Comment by atomicptr** [comment]
Thats actually a good idea, I made an issue for that
