### ISSUE TITLE
Wrong stats for Inferno's Arrow

### ISSUE THREAD

**Issue by MatthewSbar** [atomicptr/dauntless-builder-reforged#72]
Inferno's Arrow gives +1 Overpower and +1 Aetherhunter, but the site says +2 Overpower

Screenshot for proof/reference: https://puu.sh/CB1ij.jpg

**Comment by atomicptr** [comment]
I'm pretty sure this is a bug ingame because the other inferno weapons have the same stats, I reported this to phxlabs as well.

**Comment by atomicptr** [comment]
Thanks for your report, this issue was indeed a bug within the game, which Phlabs fixed with OB 0.6.6

    Fixed a bug where the Scorchstone Pike had mismatched perks after reaching level 6
    (Overpower/Aetherhunter instead of 2x Overpower like other Scorchstone weapons).

https://playdauntless.com/patch-notes/ob-0-6-6
