### ISSUE TITLE
Better Repeater part selection UI

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/dauntless-builder-reforged#74]
It should probably also get something like a tier filter and maybe a search.

**Comment by adaliszk** [comment]
Something similar what the game has would be good I think:
![IMG_20190315_131018](https://user-images.githubusercontent.com/5189131/54430445-e69d3280-4723-11e9-827e-c85b4b2236c2.jpg)

**Comment by atomicptr** [comment]
Since the repeater gets a rework very soon (which adds a new part slot, so it will have 5) this is off for now anyway :)

**Comment by adaliszk** [comment]
Gotcha, I wanted to grab one of the tickets and do it before I start work on a new feature :wink:

**Comment by atomicptr** [comment]
I guess this is useless now
