### ISSUE TITLE
Fireblades wrong cell slot

### ISSUE THREAD

**Issue by torcher999** [atomicptr/dauntless-builder-reforged#78]
Fireblades have a Utility cell slot in the builder instead of a Defense slot as seen in-game.
![image](https://user-images.githubusercontent.com/48727547/54622066-25572380-4a69-11e9-9928-84724b4f13b2.png)
![image](https://user-images.githubusercontent.com/48727547/54622156-5e8f9380-4a69-11e9-91d1-64fb01fdd500.png)

**Comment by atomicptr** [comment]
Thanks for reporting this, is fixed and should be live within a few minutes.
