### ISSUE TITLE
Add a level picker

### ISSUE THREAD

**Issue by squizza1900** [atomicptr/dauntless-builder-reforged#86]
### Feature summary

Amazing work u have done. But in the guild I'm part of we have many noobs just wondering if you can set it up so we can make builds with the lower ranked stiff. Thanks

**Comment by atomicptr** [comment]
Yeah now that leveling gear and endgame gear is the same I see why this is useful for level builds. After #87 is merged, I want to add a level picker.

**Comment by IvanKarpan** [comment]
Although it seems that it'd be enough to just have the levels that matter in terms of perk values (Base, +6 and +10) - for non-repeaters weapons and armour that is.

**Comment by squizza1900** [comment]
> Although it seems that it'd be enough to just have the levels that matter in terms of perk values (Base, +6 and +10) - for non-repeaters weapons and armour that is.

Sounds like a great idea
