### ISSUE TITLE
Repeater part effects should be able to scale with level

### ISSUE THREAD

**Issue by atomicptr** [atomicptr/dauntless-builder-reforged#93]

**Comment by NitroGenX1** [comment]
It would be better if Repeaters parts could all be scaled individually. People often use +1 barrels with +15 parts as it does more damage than a +15 barrel if u counter the behemoth's element.

**Comment by ZweetPanda** [comment]
@atomicptr This issue could be closed as the repeaters got an overhaul in 1.7.3?
